name: PJN Monitor - Verificación Automática

on:
  schedule:
    # Ejecutar cada 30 minutos
    - cron: '*/30 * * * *'
  workflow_dispatch: # Permite ejecutar manualmente desde GitHub
  push:
    branches: [ main, master ] # Para testing inicial

jobs:
  check-notifications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Instalar dependencias
      run: npm ci
    
    - name: Instalar Playwright
      run: |
        npx playwright install --with-deps chromium
        npx playwright install-deps
    
    - name: Crear directorio de datos
      run: mkdir -p ./data/cookies
    
    - name: Verificar estado actual
      run: |
        echo "Contenido de ./data:"
        ls -la ./data/ || echo "Directorio data no existe"
        echo "Base de datos existe:" 
        ls -la ./data/database.sqlite || echo "database.sqlite no existe"
        echo "Cookies existen:"
        ls -la ./data/cookies/ || echo "cookies no existen"
    
    - name: Ejecutar verificación
      env:
        PJN_USERNAME: ${{ secrets.PJN_USERNAME }}
        PJN_PASSWORD: ${{ secrets.PJN_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        NODE_ENV: production
        HEADLESS_MODE: true
      run: npm run check:now
    
    # Ya no necesitamos commits - Supabase persiste automáticamente
    
    - name: Guardar logs en caso de error
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: ./data/logs/
        retention-days: 7